services:
  n8n:
    build:
      context: ./overrides
      dockerfile: Dockerfile.n8n-custom
      args:
        N8N_TAG: ${N8N_TAG}
    environment:
      - N8N_ENABLE_EXTERNAL_MODULES=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=yahoo-finance2
  caddy:
    volumes:
      - ./overrides/Caddyfile.local:/etc/caddy/Caddyfile:ro
